---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install core packages
    package:
      name: 
        - htop
        - tmux
        - vim

  - name: copy dockerenvar file
    copy:
      src: files/dockerenvar
      dest: /etc/environment
      owner: root
      group: root

