- name: Create docker-compose directory
  file:
    path: /home/docks/docker
    state: directory
    owner: docks
    group: docks
    mode: u=rwx,g=rwx,o=rx

- name: Create docker container persistent data directory
  file:
    path: /home/docks/condata
    state: directory
    owner: docks
    group: docks
    mode: u=rwx,g=rwx,o=rx

- name: Create temporary docker-compose directory
  file:
    path: /home/docks/tempdocker
    state: directory
    owner: docks
    group: docks
    mode: u=rwx,g=rwx,o=rx

- name: Create temporary docker data directory
  file:
    path: /home/docks/tempcondata
    state: directory
    owner: docks
    group: docks
    mode: u=rwx,g=rwx,o=rx

- name: Create Duplicati bootstrap docker-compose
  copy:
    src: files/DupliDocker.yml
    dest: /home/docks/tempdocker/docker-compose.yml
