- name: Create docker-compose directory
  file:
    path: /home/ace/docker
    state: directory
    mode: u+rw,g-r,o-r

- name: Create docker container persistent data directory
  file:
    path: /home/ace/condata
    state: directory
    mode: u+rw,g-r,o-r
